import db from './db.js';

const DEFAULT_PAGE_SIZE = 20;

export async function createProduct(product) {
  const {
    device_type_id,
    product_name,
    purchase_date,
    location_id = null,
    status = 'available',
    details = null,
    qr_code = null,
    is_retired = 0
  } = product;

  // Ensure qr_code exists - if not provided, it should have been generated by the caller
  if (!qr_code) {
    throw new Error('qr_code is required when creating a product');
  }

  const [result] = await db.query(
    `INSERT INTO products 
      (device_type_id, product_name, purchase_date, location_id, status, details, qr_code, is_retired)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
    [device_type_id, product_name, purchase_date, location_id, status, details, qr_code, is_retired]
  );

  return { id: result.insertId };
}

export async function listProducts({ page = 1, limit = DEFAULT_PAGE_SIZE } = {}) {
  const safeLimit = Math.min(Number(limit) || DEFAULT_PAGE_SIZE, DEFAULT_PAGE_SIZE);
  const safePage = Math.max(Number(page) || 1, 1);
  const offset = (safePage - 1) * safeLimit;

  const [[{ total }]] = await db.query(
    'SELECT COUNT(*) AS total FROM products WHERE is_retired = 0'
  );

  // Join with device_types and locations to get their names
  // Also join with borrow_history to get current borrower info if borrowed
  const [rows] = await db.query(
    `SELECT 
       p.id, 
       p.device_type_id, 
       p.product_name, 
       p.purchase_date, 
       p.location_id, 
       p.status, 
       p.details, 
       p.qr_code, 
       p.is_retired, 
       p.created_at, 
       p.updated_at,
       dt.type_name,
       l.location_name,
       bh.borrower_id AS current_borrower_id,
       CONCAT(u.first_name, ' ', u.last_name) AS current_borrower_name,
       bh.borrow_date AS current_borrow_date,
       bh.estimated_return_date
     FROM products p
     LEFT JOIN device_types dt ON p.device_type_id = dt.id
     LEFT JOIN locations l ON p.location_id = l.id
     LEFT JOIN borrow_history bh ON p.id = bh.product_id AND bh.actual_return_date IS NULL
     LEFT JOIN users u ON bh.borrower_id = u.id
     WHERE p.is_retired = 0
     ORDER BY p.id DESC
     LIMIT ? OFFSET ?`,
    [safeLimit, offset]
  );

  const totalPages = Math.max(Math.ceil(total / safeLimit), 1);

  return {
    items: rows,
    pagination: {
      page: safePage,
      limit: safeLimit,
      totalItems: total,
      totalPages
    }
  };
}

export async function getProductById(id) {
  const [rows] = await db.query(
    `SELECT 
       p.id, 
       p.device_type_id, 
       p.product_name, 
       p.purchase_date, 
       p.location_id, 
       p.status, 
       p.details, 
       p.qr_code, 
       p.is_retired, 
       p.created_at, 
       p.updated_at,
       dt.type_name,
       l.location_name,
       bh.borrower_id AS current_borrower_id,
       CONCAT(u.first_name, ' ', u.last_name) AS current_borrower_name,
       bh.borrow_date AS current_borrow_date,
       bh.estimated_return_date
     FROM products p
     LEFT JOIN device_types dt ON p.device_type_id = dt.id
     LEFT JOIN locations l ON p.location_id = l.id
     LEFT JOIN borrow_history bh ON p.id = bh.product_id AND bh.actual_return_date IS NULL
     LEFT JOIN users u ON bh.borrower_id = u.id
     WHERE p.id = ? AND p.is_retired = 0`,
    [id]
  );
  return rows[0] || null;
}

export async function updateProduct(id, updates) {
  const allowed = ['device_type_id', 'product_name', 'purchase_date', 'location_id', 'status', 'details', 'is_retired'];
  // Note: qr_code is NOT in the allowed fields - it should never be updated once created
  const fields = [];
  const values = [];

  for (const key of allowed) {
    if (Object.prototype.hasOwnProperty.call(updates, key)) {
      fields.push(`${key} = ?`);
      values.push(updates[key]);
    }
  }

  if (fields.length === 0) {
    return { affectedRows: 0 };
  }

  values.push(id);

  const [result] = await db.query(
    `UPDATE products SET ${fields.join(', ')} WHERE id = ?`,
    values
  );

  return { affectedRows: result.affectedRows };
}

export async function deleteProduct(id) {
  const [result] = await db.query(
    'UPDATE products SET is_retired = 1 WHERE id = ?',
    [id]
  );
  return { affectedRows: result.affectedRows };
}
