import db from './db.js';

const DEFAULT_PAGE_SIZE = 20;

// CREATE — insert a new product
function insertProduct(productData, callback) {
  const {
    device_type_id,
    product_name,
    purchase_date,
    location_id = null,
    status = 'available',
    details = null,
    qr_code = null,
    is_retired = 0
  } = productData;

  // Ensure qr_code exists - if not provided, it should have been generated by the caller
  if (!qr_code) {
    return callback(new Error('qr_code is required when creating a product'));
  }

  db.query(
    `INSERT INTO products 
      (device_type_id, product_name, purchase_date, location_id, status, details, qr_code, is_retired)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
    [device_type_id, product_name, purchase_date, location_id, status, details, qr_code, is_retired],
    (err, result) => {
      if (err) return callback(err);
      callback(null, result.insertId);
    }
  );
}

// READ — get all products with pagination
function selectProducts(page, callback) {
  const limit = DEFAULT_PAGE_SIZE;
  const offset = (page - 1) * limit;

  db.query(
    'SELECT COUNT(*) AS count FROM products WHERE is_retired = 0',
    (err, countResult) => {
      if (err) return callback(err);

      const total = countResult[0].count;
      const totalPages = Math.ceil(total / limit);

      // Join with device_types and locations to get their names
      // Also join with borrow_history to get current borrower info if borrowed
      db.query(
        `SELECT 
           p.id, 
           p.device_type_id, 
           p.product_name, 
           p.purchase_date, 
           p.location_id, 
           p.status, 
           p.details, 
           p.qr_code, 
           p.is_retired, 
           p.created_at, 
           p.updated_at,
           dt.type_name,
           l.location_name,
           bh.borrower_id AS current_borrower_id,
           CONCAT(u.first_name, ' ', u.last_name) AS current_borrower_name,
           bh.borrow_date AS current_borrow_date,
           bh.estimated_return_date
         FROM products p
         LEFT JOIN device_types dt ON p.device_type_id = dt.id
         LEFT JOIN locations l ON p.location_id = l.id
         LEFT JOIN borrow_history bh ON p.id = bh.product_id AND bh.actual_return_date IS NULL
         LEFT JOIN users u ON bh.borrower_id = u.id
         WHERE p.is_retired = 0
         ORDER BY p.id DESC
         LIMIT ? OFFSET ?`,
        [limit, offset],
        (err2, rows) => {
          if (err2) return callback(err2);
          callback(null, {
            products: rows,
            totalPages,
            page
          });
        }
      );
    }
  );
}

// READ — get single product by ID
function selectProductById(id, callback) {
  db.query(
    `SELECT 
       p.id, 
       p.device_type_id, 
       p.product_name, 
       p.purchase_date, 
       p.location_id, 
       p.status, 
       p.details, 
       p.qr_code, 
       p.is_retired, 
       p.created_at, 
       p.updated_at,
       dt.type_name,
       l.location_name,
       bh.borrower_id AS current_borrower_id,
       CONCAT(u.first_name, ' ', u.last_name) AS current_borrower_name,
       bh.borrow_date AS current_borrow_date,
       bh.estimated_return_date
     FROM products p
     LEFT JOIN device_types dt ON p.device_type_id = dt.id
     LEFT JOIN locations l ON p.location_id = l.id
     LEFT JOIN borrow_history bh ON p.id = bh.product_id AND bh.actual_return_date IS NULL
     LEFT JOIN users u ON bh.borrower_id = u.id
     WHERE p.id = ? AND p.is_retired = 0`,
    [id],
    (err, rows) => {
      if (err) return callback(err);
      callback(null, rows[0] || null);
    }
  );
}

// UPDATE — modify an existing product
function updateProduct(id, fields, callback) {
  const allowed = ['device_type_id', 'product_name', 'purchase_date', 'location_id', 'status', 'details', 'is_retired'];
  // Note: qr_code is NOT in the allowed fields - it should never be updated once created
  const updateFields = [];
  const values = [];

  for (const key of allowed) {
    if (Object.prototype.hasOwnProperty.call(fields, key)) {
      updateFields.push(`${key} = ?`);
      values.push(fields[key]);
    }
  }

  if (updateFields.length === 0) {
    // No fields to update, just return the current product
    return selectProductById(id, callback);
  }

  values.push(id);

  db.query(
    `UPDATE products SET ${updateFields.join(', ')} WHERE id = ?`,
    values,
    (err, result) => {
      if (err) return callback(err);
      if (result.affectedRows === 0) {
        return callback(null, null);
      }
      // Return the updated product
      selectProductById(id, callback);
    }
  );
}

// DELETE — remove a product
function deleteProduct(id, callback) {
  db.query("DELETE FROM products WHERE id = ?", [id], (err, result) => {
    if (err) return callback(err);
    callback(null, result.affectedRows > 0);
  });
}

const products = {
  insertProduct,
  selectProducts,
  selectProductById,
  updateProduct,
  deleteProduct
};

export default products;

